<?php

namespace Alexandreo\ItauBoleto\Client\Requests\PostBoletos;

class InstrucaoCobranca implements \Alexandreo\ItauBoleto\Client\ItauRequest
{

    /**
     * @var number
     * Código da instrução de Cobrança onde o beneficiário pode mandar até 3 instruções.
     * 1 PROTESTO
     * 2 NEGATIVACAO
     * 3 PROTESTO FALIMENTAR
     * 4 NÃO PROTESTAR
     * 5 NAO NEGATIVAR
     * 7 NAO RECEBER APOS VENCIMENTO 8 BAIXAR 25 COBRAR JUROS APOS 15 DIAS DA EMISSAO 500 ENTRADA EM NEGATIVAÇAO
     * EXPRESSA 502 TEM DIA DA GRAÇA 503 NAO RECEBER ANTES DO VENCIMENTO 506 TEM DIA DA GRACA-VENCIDO COBRAR ENC
     * MORA 509 RECEBER CONFORME INSTRUÇÕES NO PROPRIO TITULO 511 RECEBER ATE O ULTIMO DIA DO MES DE VENCIMENTO 512
     * CONCEDER DESCONTO MESMO APOS VENCIMENTO 514 CONCEDER DESCONTO CONFORME NOTA DE CREDITO 530 APOS VENCIMENTO
     * CONSULTAR A AGENCIA BENEFICIARIO 539 SUJEITO A PROTESTO SE NAO FOR PAGO NO VENCIMENTO 540 COBRANÇA NEGOCIADA
     * PAGAVEL SOMENTE REDE BANCARIA 552 PAGAMENTO SOMENTE POR ESTE BOLETO E REDE BANCARIA 553 PAGADOR PODE OPTAR POR
     * ABATIMENTO DE 1,5% DO IRRF 554 APOS VENCIMENTO, PAGAVEL SOMENTE NA EMPRESA 555 EXCLUIDO
     * ATENDIMENTO NO PS HOSP. 9 DE JULHO 556 CENTRAL ELETRONICA DE INFORMACOES 0800-543.3722 557 SOMAR
     * VALOR DO TITULO AO VALOR MORA/MULTA 559 COBRANCAPRADA@CSN.COM.BR OU (11)4932-1610/1656 630 TITULO CEDIDO
     * FIDUCIARIAMENTE AO BANCO LEMON S/A. 945 APOS VCTO LIGUE 0800-177172 948 P/ OBTER EXTRATO ACESSE WWW.CIEE.ORG.BR 960
     * DESCONSIDERAR ANTERIOR. PAGAR SOMENTE COM ESTE 961 TITULO ENTREGUE EM PENHOR EM FAVOR DO BENEFICIARIO 962
     * TITULO TRANSFERIDO A FAVOR DO BENEFICIARIO 964 ANTECIPE SUAS PARCELAS COM DESCONTO 965 REAJ.ANS: 6,76%
     * OFICIO:GGEFP/ANS-387/2009 968 IRPJ 2,4%, CSSL 1%, PIS 0,65% E COFINS 3% 976 DIREITO DE CREDITO CEDIDO AO
     * FIDC SUZANO PETR. 977 DIREITO DE CREDITO CEDIDO AO BENEFICIARIO 980 SOMENTE RECEBER COM CHEQUE DE EMISSAO DO
     * PAGADOR 981 VALOR CEDIDO EM FIDUCIA AO ITAU 982 CREDITO CEDIDO 983 OPERAÇAO REFERENTE A VENDOR 984 VALOR DA
     * IDA ENGLOBA MULTA DE 10% PRO RATA 989 DUPLICATA / FATURA Nº 990 APOS VENCTO CONSULTAR CIRCULAR SC-7
     * ANEXO N-82 991 PLANO DE CAPITALIZACAO - RETORNO DE RECURSOS 992 CASO VENDA UNIDADE, EFETUAR PAGTO APOS 24 HORAS
     * 993 O DESCONTO/ABATIMENTO REFERE-SE A RETENCAO DE IR 994 ANTES DO VCTO PAGAVEL ITAU, BRADESCO OU UNIBANCO 995 NO
     * VCTO, PAGAVEL EM QUALQUER AGENCIA BANCARIA 996 APOS O VCTO 15 DIAS PAGAVEL NAS AGENCIAS DO ITAU 997 REGIME ESPECIAL
     * AUTORIZADO PELO PROCESSO 998 VALOR EMPENHADO AO ITAU.
     */
    public $codigo_instrucao_cobranca = 4;
    /**
     * @var string
     * Quantidade de dias requisitado pela instrução.
     */
    public $quantidade_dias_instrucao_cobranca;
    /**
     * @var boolean
     * Indicador se será dia útil ou corrido
     */
    public $dia_util;

}